openapi: "3.0.3"
info:
  title: openapi-tryout
  description: Try OpenAPI 3
  version: "0.1"

servers:
  - url: http://localhost:8001/api/v1

paths:
  /echo:
    $ref: "./services/echo.yaml#/paths/~1echo"
  /account:
    $ref: "./services/account.yaml#/paths/~1account"
